project:
  type: website

website:
  title: "Constantin KÃ¼hne"
  navbar:
    left:
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      # - href: blog.qmd
      #   text: Blog

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



